use_frameworks!

platform :ios, '10.0'

target 'CIImageLoaderDemo' do

#  pod 'CloudInfinite/CloudInfinite',      path:'../'
  pod 'CloudInfinite',                    path:'../'
  pod 'CloudInfinite/TPG',                path:'../'
  pod 'CloudInfinite/SDWebImage-TPG',     path:'../'
  pod 'CloudInfinite/Loader',             path:'../'

end
